require:
  - test/setup-mocha.js
  - ts-node/register
  - tsconfig-paths/register
ui: bdd
reporter: spec
bail: true
full-trace: true
watch-extensions:
  - tsx
  - ts
colors: true
recursive: true
timeout: 5000
exit: true
